### ISSUE TITLE
yarn build fail di node_env=production

### ISSUE THREAD

**Issue by asasmoyo** [devlover-id/plan-e#6]
```
bejo@staging:~/webapp/releases/1546829383$ /usr/local/nodejs-binary/bin/yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.38s.
bejo@staging:~/webapp/releases/1546829383$ /usr/local/nodejs-binary/bin/yarn run build
yarn run v1.12.3
$ next build
{ Error: Cannot find module 'next-plugin-styled-icons'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/bejo/webapp/releases/1546829383/next.config.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadConfig (/home/bejo/webapp/releases/1546829383/node_modules/next/dist/server/config.js:47:28)
    at _callee2$ (/home/bejo/webapp/releases/1546829383/node_modules/next/dist/build/index.js:52:42)
    at tryCatch (/home/bejo/webapp/releases/1546829383/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/bejo/webapp/releases/1546829383/node_modules/regenerator-runtime/runtime.js:288:22) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

step reproduce:

```
export NODE_ENV=production
yarn install
yarn run build
```

**Comment by damaera** [comment]
https://github.com/devlover-id/aku-aku/commit/0ccba151da214a52b80ed2d4019d1f3fe41e0d97

dengan cara mindah, dari dev dependencies, ke dependencies
